name: presto
description: "Sistema de prestamos bibliotecarios"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  animate_do: ^5.1.0
  flutter_native_splash: ^2.4.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/presto_logo2.jpeg
    - assets/images/splash_screen_presto.png
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/presto_logo2.jpeg
  min_sdk_android: 21 
 
flutter_native_splash:
  color: "#fffef9"
  image: assets/images/splash_screen_presto.png
  android_gravity: center
  android: true
  ios: true
  android_12:
    color: "#fffef9"
    image: assets/images/splash_screen_presto.png
    icon_background_color: "#C9B6FF"